### ISSUE TITLE
Does not work with 2.2.8

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-reports#8]
I updated from 2.2.7 to 2.2.8. After that I could no longer access the configuration section of the store. I keep getting redirected to the dashboard.

Issue also reported here: https://github.com/magento/magento2/issues/21982

### Preconditions

1. Magento: 2.2.8
2. PHP: 7.1
3. MySQL: mysql  Ver 15.1 Distrib 10.1.37-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### Steps to reproduce

1. Upgraded from 2.2.7 to 2.2.8
2. Enter admin panel
3. go to configuration section

### Expected result

1. Enter configuration section

### Actual result

1. Redirect to dashboard

**Comment by crankycyclops** [comment]
I've also experienced this as well. Temporary solution proposed was to disable the module, but I'm using Mageplaza_SocialLogin, which depends on it.

**Comment by thaimageplaza** [comment]
Hi OvalMedia,
I’m not sure that I can understand your issue/question, so could you please explain your problem in more details/ steps by steps to replicate the problem and send me some screenshots?
I really hope for your cooperation. Thank you!

**Comment by OvalMedia** [comment]
I don't know how to put it in clearer terms. As long as this module is active I cannot access some parts of the magento backend anymore. One of them is the configuration section. Whenever I try to access them I get redirected to the dashboard instead. When I disable the module the problem is gone. 
Screenshot would be useless as there is only the dashboard to see.

**Comment by tranelch** [comment]
We have this issue too, going to try using version 2.7.2, which doesn't require mageplaza/module-reports (which appears to be the source of the problem).

**Comment by crankycyclops** [comment]
I have a solution that works in the short term (hopefully this will be fixed eventually.) If you haven't yet upgraded to 2.2.8, then all you have to do is go to Admin -> Store -> Configuration -> Mage Plaza Extensions -> Reports and set "Module Enable" to No. Then, save your config, clear your cache, and then once you update to 2.2.8, this bug shouldn't be present.

If you've already upgraded to 2.2.8 and are stuck, you can still fix this, but the solution I came up with is a little more wonky.

First, browse to the extension's folder (for me, having installed via composer, it's in vendor/mageplaza/module-reports) and move etc/adminhtml/routes.xml to another folder. Then, clear your cache, run setup:upgrade and di:compile (not sure if these steps are necessary), and login to your admin.

You'll get a 404 error, but will still have access to the menu on the left, and can then browse unhindered to the module's configuration. Turn it off per the setting I detailed above, save, clear your cache, then click the dashboard button on the left to confirm that the admin route is back normal.

Now, you can restore routes.xml, and the next time you login, you'll be back to the normal dashboard and will be able to browse the admin normally.

My guess is there's an issue in the controller, but once I figured out how to turn the dashboard off without actually disabling the module (since it's a requirement for the social extension), I didn't bother digging further.

**Comment by thaimageplaza** [comment]
The issue has been solved in the develop branch.
https://github.com/mageplaza/magento-2-reports/commit/829ecef418c00f607db275a2bc511e9a8de976d6
Please check again. Thank all!

**Comment by thaimageplaza** [comment]
Closed due no response within 7 days.

**Comment by tales-desde-mileto** [comment]
This fix only works with 2.2.8
In version 2.2.9 it does not work.
Fix problem (Plugin/Config.php):
if (!$result && $this->helper->versionCompare('2.2.8', '='))
Perhaps it will solve with something like:
if (!$result && $this->helper->versionCompare('2.2.8', '>='))

I have tested and works ok in 2.2.9
Thanks a lot
